### ISSUE TITLE
👏 

### ISSUE THREAD

**Issue by jzwood** [kmurph73/doctests-via-ava#3]
I'm really glad this package exists – thanks for making it!
Would you mind adding the link to this git repo to the NPM package?

**Comment by kmurph73** [comment]
Thank you, I really appreciate it.  Wasn't too difficult to implement, but it's been surprisingly useful.  Added the `homepage` link to package.json ... that seems to have done it: https://www.npmjs.com/package/doctests-via-ava

**Comment by jzwood** [comment]
Thanks!!!!!
